POST https://auth.just2trade.com/connect/auth HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code=CfDJ8HxIlAwlw0BMt29T7xAyUxAp_l5XfkxZWHoIut1uE6ssh92zbZoXNoMTCjCNrR70k1mdZf739uoFtrj__yv4GmLCUJV-YI3AFIaRfr46Bsry0wTJu4QpV3gOi2VBeu8LrgHmrfWXiEPPVSQTUYAlx_UDM_NjTTqkmN8AD8TOYaHHLtqxYTUUtK57V_6i-orhS9X2N2UTglDyJCjwFo4_S_-iH3pIA-aPuyy4HU_hefud-rhKDwE1_1klR03PgSbJkY1yHWpK0pPaffe_3Yqsr26sUIa6w_Nls3nJjrvMemmu9RyiE0f9WBKljBm6k6Q_1ryppZX09gPxfNqeWqyMMpnKz8gwxkcLhOVi2Vc49gLlE48uVgtrTrmjKg7lR2A2A-WRms6ur7NpwXJQKVhhg31NJJQlR9QlZsixlOzPGtJYhPQOBgjjXv2oIST8Qb7dBoxLLdvffhBgLdM1KmHs9rxEqFHEVr-3-CyRjM7LSswvpDVbG7wfOmmd-5IFqhnRaKxLO3ruUVU2GuQ09eMk4MR-75UL2sc5b_ILv8ue3x1CVosshOC9RN9ILXgetyLMu-YET4R3_zMNnLB4ogH1T9aLXO5seapRnyAg6XbvL1DgK_-2IpAi50yJoDLuDZ22dwPiYP0t5kbOz3YEOBdRqZ-sVceXm0rEz5B79plpboCJ0yVfPB8fX6_e-W59I_alCHiKMXTJJ04nbusuf_QQk5Em0qF0f9iLqmrlqfVDi3VHLhOyoK9xiaTNb9fM1XsyIpXhJrjSVEKFUu-Dgwf_cI2jF9fVJWJ_rXxVZw9Z6O-Q1aseH2PERAdctSD2jnAXMx5LvATguf_EWXuJM5V3uaJ2FPv9O_pidc47LE6pGosfYI_cGO6--84BoNLA7S4m9orH2j8ivqDtekwiNkFz_ldzx0eBKQx3JMkmahEVHxe0&client_id=test
